# Generated by Django 2.2 on 2020-11-18 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='hunter',
            new_name='creator',
        ),
    ]
